
##  Loading Libraries & Dataset
#

In [18]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
    
from IPython.display import display  # print() can only print text , for tabular multiple tabular 
                                     # dataframes to print in a single cell we use display()

import warnings 
warnings.filterwarnings('ignore') # as some functions maybe depricated in future versions to ignore the 
                                  # messages of these updates we ignore them}

In [19]:
df = pd.read_csv('../data/01_cleaned_heart_data.csv')
display(df.head())

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140.0,289.0,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160.0,180.0,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130.0,283.0,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138.0,214.0,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150.0,195.0,0,Normal,122,N,0.0,Up,0

#
## 3) Data Preprocessing
#

##
### 3.1 - Label Encoding Binary Categorical Variables
##

- ML Algorithms cannot understand and handle text like ATA / Normal / M / F 
- We need to encode them to numbers 
- For Binary Categories ( 2 values like Male/Female) , we encode them to 0/1 manaully ..

In [20]:
categorical_df = df.select_dtypes(include = 'object')
display(categorical_df.head(1))

categorical_columns = categorical_df.columns
display(categorical_df.columns)

  Sex ChestPainType RestingECG ExerciseAngina ST_Slope
0   M           ATA     Normal              N       Up

Index(['Sex', 'ChestPainType', 'RestingECG', 'ExerciseAngina', 'ST_Slope'], dtype='object')

- Above are the categorical Columns of the dataset

In [21]:
for col in categorical_columns : 
    unique_count  = df[col].nunique()   # df['col_name'].nunique() gives us total number of unique values in column
    unique_values = df[col].unique()    # df['col_name'].unique() gives us list of unique values of required column
    print(f"Column : {col:<20} | Unique Count: {unique_count:<12} | Values: {unique_values}")

Column : Sex                  | Unique Count: 2            | Values: ['M' 'F']
Column : ChestPainType        | Unique Count: 4            | Values: ['ATA' 'NAP' 'ASY' 'TA']
Column : RestingECG           | Unique Count: 3            | Values: ['Normal' 'ST' 'LVH']
Column : ExerciseAngina       | Unique Count: 2            | Values: ['N' 'Y']
Column : ST_Slope             | Unique Count: 3            | Values: ['Up' 'Flat' 'Down']

##### Binary Categorical Columnns     :  Sex / ExerciseAngina
##### Multi-Class Categorical Columns :  ChestPainType / RestingECG / ST_Slope

In [22]:
sex_mapping = {
    'M': 1 ,
    'F': 0 
}
df['Sex'] = df['Sex'].map(sex_mapping)

angina_mapping = {
    'Y': 1 , 
    'N': 0
}
df['ExerciseAngina'] = df['ExerciseAngina'].map(angina_mapping)

In [25]:
display(df.head())
display(df[['Sex', 'ExerciseAngina']].inf)

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,1,ATA,140.0,289.0,0,Normal,172,0,0.0,Up,0
1,49,0,NAP,160.0,180.0,0,Normal,156,0,1.0,Flat,1
2,37,1,ATA,130.0,283.0,0,ST,98,0,0.0,Up,0
3,48,0,ASY,138.0,214.0,0,Normal,108,1,1.5,Flat,1
4,54,1,NAP,150.0,195.0,0,Normal,122,0,0.0,Up,0

- We can verify here binary categorical variables are encoded

##
### 3.1 - One Hot Encoding Multi-Class Categorical Variables
##